name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Building frontend Image
        run: |
          cd Frontend
          ls
          docker build . -t epa_frontend_img -f Dockerfile
        
      - name: Building backend Image
        run: docker build . -t epa_backend_img -f backend/Dockerfile
        
      - name: Pushing frontend to dockerhub 
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker push reeceqa/epa_frontend_img:latest
          docker push reeceqa/epa_backend_img:latest
