name: CI

on:
  push:
    branches:
      - Dev


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Building frontend Image
        run: |
          docker build -t reeceqa/epa_frontend ./Frontend/
        
      - name: Building backend Image
        run: | 
          docker build -t reeceqa/epa_backend ./Backend/
        
      - name: Pushing frontend to dockerhub 
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker push reeceqa/epa_frontend:latest
          docker push reeceqa/epa_backend:latest
